// All countries with dial codes, sorted with Arab/common countries first, then alphabetically
// nameAr is provided for Arab League countries and popular ones; others fall back to nameEn

export const COUNTRIES = [
  // Arab countries first
  { code: "sa", dialCode: "+966", flag: "🇸🇦", nameEn: "Saudi Arabia",         nameAr: "السعودية",     minLength: 9,  maxLength: 9  },
  { code: "ae", dialCode: "+971", flag: "🇦🇪", nameEn: "UAE",                   nameAr: "الإمارات",     minLength: 9,  maxLength: 9  },
  { code: "eg", dialCode: "+20",  flag: "🇪🇬", nameEn: "Egypt",                 nameAr: "مصر",          minLength: 10, maxLength: 10 },
  { code: "kw", dialCode: "+965", flag: "🇰🇼", nameEn: "Kuwait",                nameAr: "الكويت",       minLength: 8,  maxLength: 8  },
  { code: "qa", dialCode: "+974", flag: "🇶🇦", nameEn: "Qatar",                 nameAr: "قطر",          minLength: 8,  maxLength: 8  },
  { code: "bh", dialCode: "+973", flag: "🇧🇭", nameEn: "Bahrain",               nameAr: "البحرين",      minLength: 8,  maxLength: 8  },
  { code: "om", dialCode: "+968", flag: "🇴🇲", nameEn: "Oman",                  nameAr: "عُمان",        minLength: 8,  maxLength: 8  },
  { code: "jo", dialCode: "+962", flag: "🇯🇴", nameEn: "Jordan",                nameAr: "الأردن",       minLength: 9,  maxLength: 9  },
  { code: "lb", dialCode: "+961", flag: "🇱🇧", nameEn: "Lebanon",               nameAr: "لبنان",        minLength: 7,  maxLength: 8  },
  { code: "iq", dialCode: "+964", flag: "🇮🇶", nameEn: "Iraq",                  nameAr: "العراق",       minLength: 10, maxLength: 10 },
  { code: "sy", dialCode: "+963", flag: "🇸🇾", nameEn: "Syria",                 nameAr: "سوريا",        minLength: 9,  maxLength: 9  },
  { code: "ps", dialCode: "+970", flag: "🇵🇸", nameEn: "Palestine",             nameAr: "فلسطين",       minLength: 9,  maxLength: 9  },
  { code: "ma", dialCode: "+212", flag: "🇲🇦", nameEn: "Morocco",               nameAr: "المغرب",       minLength: 9,  maxLength: 9  },
  { code: "tn", dialCode: "+216", flag: "🇹🇳", nameEn: "Tunisia",               nameAr: "تونس",         minLength: 8,  maxLength: 8  },
  { code: "dz", dialCode: "+213", flag: "🇩🇿", nameEn: "Algeria",               nameAr: "الجزائر",      minLength: 9,  maxLength: 9  },
  { code: "ly", dialCode: "+218", flag: "🇱🇾", nameEn: "Libya",                 nameAr: "ليبيا",        minLength: 9,  maxLength: 10 },
  { code: "sd", dialCode: "+249", flag: "🇸🇩", nameEn: "Sudan",                 nameAr: "السودان",      minLength: 9,  maxLength: 9  },
  { code: "ye", dialCode: "+967", flag: "🇾🇪", nameEn: "Yemen",                 nameAr: "اليمن",        minLength: 9,  maxLength: 9  },
  { code: "so", dialCode: "+252", flag: "🇸🇴", nameEn: "Somalia",               nameAr: "الصومال",      minLength: 7,  maxLength: 8  },
  { code: "dj", dialCode: "+253", flag: "🇩🇯", nameEn: "Djibouti",              nameAr: "جيبوتي",       minLength: 8,  maxLength: 8  },
  { code: "km", dialCode: "+269", flag: "🇰🇲", nameEn: "Comoros",               nameAr: "جزر القمر",    minLength: 7,  maxLength: 7  },
  { code: "mr", dialCode: "+222", flag: "🇲🇷", nameEn: "Mauritania",            nameAr: "موريتانيا",    minLength: 8,  maxLength: 8  },

  // Rest of the world alphabetically
  { code: "af", dialCode: "+93",  flag: "🇦🇫", nameEn: "Afghanistan",           nameAr: "أفغانستان",   minLength: 9,  maxLength: 9  },
  { code: "al", dialCode: "+355", flag: "🇦🇱", nameEn: "Albania",               nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "ad", dialCode: "+376", flag: "🇦🇩", nameEn: "Andorra",               nameAr: null,           minLength: 6,  maxLength: 9  },
  { code: "ao", dialCode: "+244", flag: "🇦🇴", nameEn: "Angola",                nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "ag", dialCode: "+1",   flag: "🇦🇬", nameEn: "Antigua & Barbuda",     nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "ar", dialCode: "+54",  flag: "🇦🇷", nameEn: "Argentina",             nameAr: null,           minLength: 10, maxLength: 11 },
  { code: "am", dialCode: "+374", flag: "🇦🇲", nameEn: "Armenia",               nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "au", dialCode: "+61",  flag: "🇦🇺", nameEn: "Australia",             nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "at", dialCode: "+43",  flag: "🇦🇹", nameEn: "Austria",               nameAr: null,           minLength: 10, maxLength: 12 },
  { code: "az", dialCode: "+994", flag: "🇦🇿", nameEn: "Azerbaijan",            nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "bs", dialCode: "+1",   flag: "🇧🇸", nameEn: "Bahamas",               nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "bd", dialCode: "+880", flag: "🇧🇩", nameEn: "Bangladesh",            nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "bb", dialCode: "+1",   flag: "🇧🇧", nameEn: "Barbados",              nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "by", dialCode: "+375", flag: "🇧🇾", nameEn: "Belarus",               nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "be", dialCode: "+32",  flag: "🇧🇪", nameEn: "Belgium",               nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "bz", dialCode: "+501", flag: "🇧🇿", nameEn: "Belize",                nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "bj", dialCode: "+229", flag: "🇧🇯", nameEn: "Benin",                 nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "bt", dialCode: "+975", flag: "🇧🇹", nameEn: "Bhutan",                nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "bo", dialCode: "+591", flag: "🇧🇴", nameEn: "Bolivia",               nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "ba", dialCode: "+387", flag: "🇧🇦", nameEn: "Bosnia & Herzegovina",  nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "bw", dialCode: "+267", flag: "🇧🇼", nameEn: "Botswana",              nameAr: null,           minLength: 7,  maxLength: 8  },
  { code: "br", dialCode: "+55",  flag: "🇧🇷", nameEn: "Brazil",                nameAr: null,           minLength: 10, maxLength: 11 },
  { code: "bn", dialCode: "+673", flag: "🇧🇳", nameEn: "Brunei",                nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "bg", dialCode: "+359", flag: "🇧🇬", nameEn: "Bulgaria",              nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "bf", dialCode: "+226", flag: "🇧🇫", nameEn: "Burkina Faso",          nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "bi", dialCode: "+257", flag: "🇧🇮", nameEn: "Burundi",               nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "cv", dialCode: "+238", flag: "🇨🇻", nameEn: "Cape Verde",            nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "kh", dialCode: "+855", flag: "🇰🇭", nameEn: "Cambodia",              nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "cm", dialCode: "+237", flag: "🇨🇲", nameEn: "Cameroon",              nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "ca", dialCode: "+1",   flag: "🇨🇦", nameEn: "Canada",                nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "cf", dialCode: "+236", flag: "🇨🇫", nameEn: "Central African Rep.",  nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "td", dialCode: "+235", flag: "🇹🇩", nameEn: "Chad",                  nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "cl", dialCode: "+56",  flag: "🇨🇱", nameEn: "Chile",                 nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "cn", dialCode: "+86",  flag: "🇨🇳", nameEn: "China",                 nameAr: null,           minLength: 11, maxLength: 11 },
  { code: "co", dialCode: "+57",  flag: "🇨🇴", nameEn: "Colombia",              nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "cg", dialCode: "+242", flag: "🇨🇬", nameEn: "Congo",                 nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "cd", dialCode: "+243", flag: "🇨🇩", nameEn: "DR Congo",              nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "cr", dialCode: "+506", flag: "🇨🇷", nameEn: "Costa Rica",            nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "ci", dialCode: "+225", flag: "🇨🇮", nameEn: "Côte d'Ivoire",         nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "hr", dialCode: "+385", flag: "🇭🇷", nameEn: "Croatia",               nameAr: null,           minLength: 8,  maxLength: 9  },
  { code: "cu", dialCode: "+53",  flag: "🇨🇺", nameEn: "Cuba",                  nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "cy", dialCode: "+357", flag: "🇨🇾", nameEn: "Cyprus",                nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "cz", dialCode: "+420", flag: "🇨🇿", nameEn: "Czech Republic",        nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "dk", dialCode: "+45",  flag: "🇩🇰", nameEn: "Denmark",               nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "dm", dialCode: "+1",   flag: "🇩🇲", nameEn: "Dominica",              nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "do", dialCode: "+1",   flag: "🇩🇴", nameEn: "Dominican Republic",    nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "ec", dialCode: "+593", flag: "🇪🇨", nameEn: "Ecuador",               nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "sv", dialCode: "+503", flag: "🇸🇻", nameEn: "El Salvador",           nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "gq", dialCode: "+240", flag: "🇬🇶", nameEn: "Equatorial Guinea",     nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "er", dialCode: "+291", flag: "🇪🇷", nameEn: "Eritrea",               nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "ee", dialCode: "+372", flag: "🇪🇪", nameEn: "Estonia",               nameAr: null,           minLength: 7,  maxLength: 8  },
  { code: "sz", dialCode: "+268", flag: "🇸🇿", nameEn: "Eswatini",              nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "et", dialCode: "+251", flag: "🇪🇹", nameEn: "Ethiopia",              nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "fj", dialCode: "+679", flag: "🇫🇯", nameEn: "Fiji",                  nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "fi", dialCode: "+358", flag: "🇫🇮", nameEn: "Finland",               nameAr: null,           minLength: 9,  maxLength: 11 },
  { code: "fr", dialCode: "+33",  flag: "🇫🇷", nameEn: "France",                nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "ga", dialCode: "+241", flag: "🇬🇦", nameEn: "Gabon",                 nameAr: null,           minLength: 7,  maxLength: 8  },
  { code: "gm", dialCode: "+220", flag: "🇬🇲", nameEn: "Gambia",                nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "ge", dialCode: "+995", flag: "🇬🇪", nameEn: "Georgia",               nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "de", dialCode: "+49",  flag: "🇩🇪", nameEn: "Germany",               nameAr: null,           minLength: 10, maxLength: 12 },
  { code: "gh", dialCode: "+233", flag: "🇬🇭", nameEn: "Ghana",                 nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "gr", dialCode: "+30",  flag: "🇬🇷", nameEn: "Greece",                nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "gd", dialCode: "+1",   flag: "🇬🇩", nameEn: "Grenada",               nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "gt", dialCode: "+502", flag: "🇬🇹", nameEn: "Guatemala",             nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "gn", dialCode: "+224", flag: "🇬🇳", nameEn: "Guinea",                nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "gw", dialCode: "+245", flag: "🇬🇼", nameEn: "Guinea-Bissau",         nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "gy", dialCode: "+592", flag: "🇬🇾", nameEn: "Guyana",                nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "ht", dialCode: "+509", flag: "🇭🇹", nameEn: "Haiti",                 nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "hn", dialCode: "+504", flag: "🇭🇳", nameEn: "Honduras",              nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "hk", dialCode: "+852", flag: "🇭🇰", nameEn: "Hong Kong",             nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "hu", dialCode: "+36",  flag: "🇭🇺", nameEn: "Hungary",               nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "is", dialCode: "+354", flag: "🇮🇸", nameEn: "Iceland",               nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "in", dialCode: "+91",  flag: "🇮🇳", nameEn: "India",                 nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "id", dialCode: "+62",  flag: "🇮🇩", nameEn: "Indonesia",             nameAr: null,           minLength: 9,  maxLength: 12 },
  { code: "ir", dialCode: "+98",  flag: "🇮🇷", nameEn: "Iran",                  nameAr: "إيران",        minLength: 10, maxLength: 10 },
  { code: "ie", dialCode: "+353", flag: "🇮🇪", nameEn: "Ireland",               nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "il", dialCode: "+972", flag: "🇮🇱", nameEn: "Israel",                nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "it", dialCode: "+39",  flag: "🇮🇹", nameEn: "Italy",                 nameAr: null,           minLength: 9,  maxLength: 11 },
  { code: "jm", dialCode: "+1",   flag: "🇯🇲", nameEn: "Jamaica",               nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "jp", dialCode: "+81",  flag: "🇯🇵", nameEn: "Japan",                 nameAr: null,           minLength: 10, maxLength: 11 },
  { code: "kz", dialCode: "+7",   flag: "🇰🇿", nameEn: "Kazakhstan",            nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "ke", dialCode: "+254", flag: "🇰🇪", nameEn: "Kenya",                 nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "ki", dialCode: "+686", flag: "🇰🇮", nameEn: "Kiribati",              nameAr: null,           minLength: 5,  maxLength: 8  },
  { code: "xk", dialCode: "+383", flag: "🇽🇰", nameEn: "Kosovo",                nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "kg", dialCode: "+996", flag: "🇰🇬", nameEn: "Kyrgyzstan",            nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "la", dialCode: "+856", flag: "🇱🇦", nameEn: "Laos",                  nameAr: null,           minLength: 8,  maxLength: 9  },
  { code: "lv", dialCode: "+371", flag: "🇱🇻", nameEn: "Latvia",                nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "ls", dialCode: "+266", flag: "🇱🇸", nameEn: "Lesotho",               nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "lr", dialCode: "+231", flag: "🇱🇷", nameEn: "Liberia",               nameAr: null,           minLength: 7,  maxLength: 8  },
  { code: "li", dialCode: "+423", flag: "🇱🇮", nameEn: "Liechtenstein",         nameAr: null,           minLength: 7,  maxLength: 9  },
  { code: "lt", dialCode: "+370", flag: "🇱🇹", nameEn: "Lithuania",             nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "lu", dialCode: "+352", flag: "🇱🇺", nameEn: "Luxembourg",            nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "mo", dialCode: "+853", flag: "🇲🇴", nameEn: "Macao",                 nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "mg", dialCode: "+261", flag: "🇲🇬", nameEn: "Madagascar",            nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "mw", dialCode: "+265", flag: "🇲🇼", nameEn: "Malawi",                nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "my", dialCode: "+60",  flag: "🇲🇾", nameEn: "Malaysia",              nameAr: null,           minLength: 9,  maxLength: 10 },
  { code: "mv", dialCode: "+960", flag: "🇲🇻", nameEn: "Maldives",              nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "ml", dialCode: "+223", flag: "🇲🇱", nameEn: "Mali",                  nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "mt", dialCode: "+356", flag: "🇲🇹", nameEn: "Malta",                 nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "mh", dialCode: "+692", flag: "🇲🇭", nameEn: "Marshall Islands",      nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "mu", dialCode: "+230", flag: "🇲🇺", nameEn: "Mauritius",             nameAr: null,           minLength: 7,  maxLength: 8  },
  { code: "mx", dialCode: "+52",  flag: "🇲🇽", nameEn: "Mexico",                nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "fm", dialCode: "+691", flag: "🇫🇲", nameEn: "Micronesia",            nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "md", dialCode: "+373", flag: "🇲🇩", nameEn: "Moldova",               nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "mc", dialCode: "+377", flag: "🇲🇨", nameEn: "Monaco",                nameAr: null,           minLength: 8,  maxLength: 9  },
  { code: "mn", dialCode: "+976", flag: "🇲🇳", nameEn: "Mongolia",              nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "me", dialCode: "+382", flag: "🇲🇪", nameEn: "Montenegro",            nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "mz", dialCode: "+258", flag: "🇲🇿", nameEn: "Mozambique",            nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "mm", dialCode: "+95",  flag: "🇲🇲", nameEn: "Myanmar",               nameAr: null,           minLength: 9,  maxLength: 10 },
  { code: "na", dialCode: "+264", flag: "🇳🇦", nameEn: "Namibia",               nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "nr", dialCode: "+674", flag: "🇳🇷", nameEn: "Nauru",                 nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "np", dialCode: "+977", flag: "🇳🇵", nameEn: "Nepal",                 nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "nl", dialCode: "+31",  flag: "🇳🇱", nameEn: "Netherlands",           nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "nz", dialCode: "+64",  flag: "🇳🇿", nameEn: "New Zealand",           nameAr: null,           minLength: 8,  maxLength: 10 },
  { code: "ni", dialCode: "+505", flag: "🇳🇮", nameEn: "Nicaragua",             nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "ne", dialCode: "+227", flag: "🇳🇪", nameEn: "Niger",                 nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "ng", dialCode: "+234", flag: "🇳🇬", nameEn: "Nigeria",               nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "mk", dialCode: "+389", flag: "🇲🇰", nameEn: "North Macedonia",       nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "no", dialCode: "+47",  flag: "🇳🇴", nameEn: "Norway",                nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "pk", dialCode: "+92",  flag: "🇵🇰", nameEn: "Pakistan",              nameAr: "باكستان",      minLength: 10, maxLength: 10 },
  { code: "pw", dialCode: "+680", flag: "🇵🇼", nameEn: "Palau",                 nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "pa", dialCode: "+507", flag: "🇵🇦", nameEn: "Panama",                nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "pg", dialCode: "+675", flag: "🇵🇬", nameEn: "Papua New Guinea",      nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "py", dialCode: "+595", flag: "🇵🇾", nameEn: "Paraguay",              nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "pe", dialCode: "+51",  flag: "🇵🇪", nameEn: "Peru",                  nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "ph", dialCode: "+63",  flag: "🇵🇭", nameEn: "Philippines",           nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "pl", dialCode: "+48",  flag: "🇵🇱", nameEn: "Poland",                nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "pt", dialCode: "+351", flag: "🇵🇹", nameEn: "Portugal",              nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "ro", dialCode: "+40",  flag: "🇷🇴", nameEn: "Romania",               nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "ru", dialCode: "+7",   flag: "🇷🇺", nameEn: "Russia",                nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "rw", dialCode: "+250", flag: "🇷🇼", nameEn: "Rwanda",                nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "kn", dialCode: "+1",   flag: "🇰🇳", nameEn: "Saint Kitts & Nevis",   nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "lc", dialCode: "+1",   flag: "🇱🇨", nameEn: "Saint Lucia",           nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "vc", dialCode: "+1",   flag: "🇻🇨", nameEn: "Saint Vincent",         nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "ws", dialCode: "+685", flag: "🇼🇸", nameEn: "Samoa",                 nameAr: null,           minLength: 5,  maxLength: 7  },
  { code: "sm", dialCode: "+378", flag: "🇸🇲", nameEn: "San Marino",            nameAr: null,           minLength: 6,  maxLength: 10 },
  { code: "st", dialCode: "+239", flag: "🇸🇹", nameEn: "São Tomé & Príncipe",   nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "sn", dialCode: "+221", flag: "🇸🇳", nameEn: "Senegal",               nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "rs", dialCode: "+381", flag: "🇷🇸", nameEn: "Serbia",                nameAr: null,           minLength: 8,  maxLength: 9  },
  { code: "sc", dialCode: "+248", flag: "🇸🇨", nameEn: "Seychelles",            nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "sl", dialCode: "+232", flag: "🇸🇱", nameEn: "Sierra Leone",          nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "sg", dialCode: "+65",  flag: "🇸🇬", nameEn: "Singapore",             nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "sk", dialCode: "+421", flag: "🇸🇰", nameEn: "Slovakia",              nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "si", dialCode: "+386", flag: "🇸🇮", nameEn: "Slovenia",              nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "sb", dialCode: "+677", flag: "🇸🇧", nameEn: "Solomon Islands",       nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "za", dialCode: "+27",  flag: "🇿🇦", nameEn: "South Africa",          nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "kr", dialCode: "+82",  flag: "🇰🇷", nameEn: "South Korea",           nameAr: null,           minLength: 9,  maxLength: 10 },
  { code: "ss", dialCode: "+211", flag: "🇸🇸", nameEn: "South Sudan",           nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "es", dialCode: "+34",  flag: "🇪🇸", nameEn: "Spain",                 nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "lk", dialCode: "+94",  flag: "🇱🇰", nameEn: "Sri Lanka",             nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "sr", dialCode: "+597", flag: "🇸🇷", nameEn: "Suriname",              nameAr: null,           minLength: 7,  maxLength: 7  },
  { code: "se", dialCode: "+46",  flag: "🇸🇪", nameEn: "Sweden",                nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "ch", dialCode: "+41",  flag: "🇨🇭", nameEn: "Switzerland",           nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "tw", dialCode: "+886", flag: "🇹🇼", nameEn: "Taiwan",                nameAr: null,           minLength: 9,  maxLength: 10 },
  { code: "tj", dialCode: "+992", flag: "🇹🇯", nameEn: "Tajikistan",            nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "tz", dialCode: "+255", flag: "🇹🇿", nameEn: "Tanzania",              nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "th", dialCode: "+66",  flag: "🇹🇭", nameEn: "Thailand",              nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "tl", dialCode: "+670", flag: "🇹🇱", nameEn: "Timor-Leste",           nameAr: null,           minLength: 7,  maxLength: 8  },
  { code: "tg", dialCode: "+228", flag: "🇹🇬", nameEn: "Togo",                  nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "to", dialCode: "+676", flag: "🇹🇴", nameEn: "Tonga",                 nameAr: null,           minLength: 5,  maxLength: 7  },
  { code: "tt", dialCode: "+1",   flag: "🇹🇹", nameEn: "Trinidad & Tobago",     nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "tr", dialCode: "+90",  flag: "🇹🇷", nameEn: "Turkey",                nameAr: "تركيا",        minLength: 10, maxLength: 10 },
  { code: "tm", dialCode: "+993", flag: "🇹🇲", nameEn: "Turkmenistan",          nameAr: null,           minLength: 8,  maxLength: 8  },
  { code: "tv", dialCode: "+688", flag: "🇹🇻", nameEn: "Tuvalu",                nameAr: null,           minLength: 5,  maxLength: 6  },
  { code: "ug", dialCode: "+256", flag: "🇺🇬", nameEn: "Uganda",                nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "ua", dialCode: "+380", flag: "🇺🇦", nameEn: "Ukraine",               nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "gb", dialCode: "+44",  flag: "🇬🇧", nameEn: "United Kingdom",        nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "us", dialCode: "+1",   flag: "🇺🇸", nameEn: "United States",         nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "uy", dialCode: "+598", flag: "🇺🇾", nameEn: "Uruguay",               nameAr: null,           minLength: 8,  maxLength: 9  },
  { code: "uz", dialCode: "+998", flag: "🇺🇿", nameEn: "Uzbekistan",            nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "vu", dialCode: "+678", flag: "🇻🇺", nameEn: "Vanuatu",               nameAr: null,           minLength: 5,  maxLength: 7  },
  { code: "va", dialCode: "+379", flag: "🇻🇦", nameEn: "Vatican City",          nameAr: null,           minLength: 6,  maxLength: 10 },
  { code: "ve", dialCode: "+58",  flag: "🇻🇪", nameEn: "Venezuela",             nameAr: null,           minLength: 10, maxLength: 10 },
  { code: "vn", dialCode: "+84",  flag: "🇻🇳", nameEn: "Vietnam",               nameAr: null,           minLength: 9,  maxLength: 10 },
  { code: "zm", dialCode: "+260", flag: "🇿🇲", nameEn: "Zambia",                nameAr: null,           minLength: 9,  maxLength: 9  },
  { code: "zw", dialCode: "+263", flag: "🇿🇼", nameEn: "Zimbabwe",              nameAr: null,           minLength: 9,  maxLength: 9  },
];

/**
 * Get the display name for a country based on locale
 */
export function getCountryName(country, isRTL) {
  return (isRTL && country.nameAr) ? country.nameAr : country.nameEn;
}

/**
 * Filter countries by search query (matches name or dial code)
 */
export function searchCountries(query, isRTL) {
  if (!query) return COUNTRIES;
  const q = query.toLowerCase().trim();
  return COUNTRIES.filter((c) => {
    const name = getCountryName(c, isRTL).toLowerCase();
    return name.includes(q) || c.dialCode.includes(q) || c.code.includes(q);
  });
}
